# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: naotaco blog.
email: naotaco+blog@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  労働の記録
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.naotaco.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.19.2"

breadcrumbs: true

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives

google:
  search_engine_id: 000296326656564113471:xfctje3nz3p

twitter:
  username: "naotaco"

og_image: /assets/images/site-logo.png

social:
  type: Person
  name: Nao Taco
  links:
    - "https://twitter.com/naotaco"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-17571325-4"

author:
  name: "Nao Taco"
  avatar: "/assets/images/site-logo.png"
  bio: "組み込み屋"
  location: "日本"
  links:
    - label: "Twitter"
    - url: https://twitter.com/naotaco"

timezone: Asia/Tokyo

category_archive:
  type: liquid
  path: /categories/

  tag_archive:
  type: liquid
  path: /tags/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
